"""Emit expose/brief-numbers.tex from results/router_eval.json.

The venture brief cites router numbers only through these macros, exactly as the
exposé cites sweep numbers only through expose/numbers.tex. Never hand-edit.

Run after ``python -m runtime.router``.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WNAME = {"A0": "Zero", "A1": "One", "A2": "Two", "A3": "Three", "ROUTER": "Router"}


def _pct(x) -> str:
    return "n/a" if x is None else f"{x * 100:.1f}\\%"


def _num(x, digits=2) -> str:
    return "n/a" if x is None else f"{x:.{digits}f}"


def main() -> None:
    report = json.loads((ROOT / "results" / "router_eval.json").read_text())
    systems = report["systems"]
    dist = report["routing_distribution"]
    lines = [
        "% Auto-generated by runtime/make_brief_numbers.py from results/router_eval.json.",
        "% Do not edit by hand.",
        f"\\newcommand{{\\routerNreq}}{{{report['n_requests']}}}",
    ]
    for variant, word in WNAME.items():
        m = systems.get(variant, {})
        lines += [
            f"\\newcommand{{\\rtMism{word}}}{{{_pct(m.get('policy_mismatch_rate'))}}}",
            f"\\newcommand{{\\rtUnsafe{word}}}{{{_pct(m.get('unsafe_approval_rate'))}}}",
            f"\\newcommand{{\\rtInj{word}}}{{{_pct(m.get('injected_unsafe_rate'))}}}",
            f"\\newcommand{{\\rtRepro{word}}}{{{_pct(m.get('repro_modal_share_mean'))}}}",
            f"\\newcommand{{\\rtCalls{word}}}{{{_num(m.get('mean_llm_calls'))}}}",
        ]
    for variant in ("A0", "A1", "A2", "A3"):
        lines.append(
            f"\\newcommand{{\\rtDist{WNAME[variant]}}}{{{dist.get(variant, 0)}}}"
        )
    out = ROOT / "expose" / "brief-numbers.tex"
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out} ({len(lines)} lines)")


if __name__ == "__main__":
    main()
