"""Emit expose/placement-numbers.tex from results-local/placement_eval.json.

The exposé and venture brief cite placement numbers only through these macros,
exactly as they cite sweep numbers through expose/numbers.tex. Never hand-edit.

Run after ``python -m runtime.placement``.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def _pct(x) -> str:
    return "n/a" if x is None else f"{x * 100:.1f}\\%"


def _num(x, digits=2) -> str:
    return "n/a" if x is None else f"{x:.{digits}f}"


def main() -> None:
    report = json.loads(
        (ROOT / "results-local" / "placement_eval.json").read_text()
    )
    m = report["systems"]["PLACEMENT"]
    lines = [
        "% Auto-generated by runtime/make_placement_numbers.py from results-local/placement_eval.json.",
        "% Do not edit by hand.",
        f"\\newcommand{{\\plNreq}}{{{report['n_requests']}}}",
        f"\\newcommand{{\\plLocalShare}}{{{_pct(report['local_share'])}}}",
        f"\\newcommand{{\\plMism}}{{{_pct(m.get('policy_mismatch_rate'))}}}",
        f"\\newcommand{{\\plUnsafe}}{{{_pct(m.get('unsafe_approval_rate'))}}}",
        f"\\newcommand{{\\plInj}}{{{_pct(m.get('injected_unsafe_rate'))}}}",
        f"\\newcommand{{\\plCalls}}{{{_num(m.get('mean_llm_calls'))}}}",
        f"\\newcommand{{\\plRepro}}{{{_pct(m.get('repro_modal_share_mean'))}}}",
    ]
    out = ROOT / "expose" / "placement-numbers.tex"
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out} ({len(lines)} lines)")


if __name__ == "__main__":
    main()
