"""Egress-aware placement: choose the autonomy level AND the execution tier.

This extends research question 4 to the on-prem runtime framing: per request,
the placement rule combines the unchanged autonomy router
(``runtime.router.route``) with an architecture-derived tier rule, stated
before any local-sweep metric was inspected:

  1. Variants whose decision is deterministic (A2/A3) run on the local tier;
     the LLM there only parses (and explains), so the runtime has no
     architectural reason to send the request outside the perimeter.
  2. LLM-owned variants (A0/A1) may use the external provider model, UNLESS
     the purchase involves personal data (``data_processing``), which must not
     leave the perimeter and therefore also runs local.

The composite system is then scored by reselecting, per request, the
ALREADY-MEASURED canonical/repro rows of the routed variant from the tier's
own cached sweep: ``results/`` for the external provider model, and
``results-local/`` for the small local model. No new LLM calls are made.

The human rung is not a third scored tier: as in the router evaluation, an
``escalate`` decision outcome IS the hand-off to a human, whichever tier
produced it.

Honesty notes (also embedded in the report):
  * All notes of ``runtime/router.py`` apply (idealized pre-parse, lexical
    injection screen, no outcome tuning, cached-row reselection).
  * The tier rule is a hand-written policy statement derived from the
    architecture (deterministic-core variants stay local; personal data never
    leaves), not a learned or outcome-tuned placement; zero personal-data
    egress is a design property of the rule, and the measured quantities are
    the resulting local-tier share and policy metrics.
  * The external comparator is one provider model, not a frontier-model
    ceiling; the local tier is one small open-weight model.

Run after both sweeps exist:
    ``python -m runtime.placement [--seed 42]``
"""
from __future__ import annotations

import argparse
import sys
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from harness.validate_results import load_rows, validate_rows  # noqa: E402
from runtime.router import (  # noqa: E402
    _policy_metrics,
    _repro_modal_mean,
    _write_report_atomic,
    route,
)
from taskgen.generator import generate  # noqa: E402
from taskgen.schema import ProcurementRequest  # noqa: E402

EXTERNAL_DIR = ROOT / "results"
LOCAL_DIR = ROOT / "results-local"


def place(req: ProcurementRequest) -> tuple[str, str, str, str]:
    """Return (variant, tier, variant_rule, tier_rule).

    Pure function of pre-decision signals; the variant comes from the
    unchanged autonomy router.
    """
    variant, variant_rule = route(req)
    if variant in ("A2", "A3"):
        return variant, "local", variant_rule, "deterministic_core_runs_local"
    if req.structured()["data_processing"]:
        return variant, "local", variant_rule, "personal_data_stays_local"
    return variant, "external", variant_rule, "external_allowed"


def _index(rows: list[dict]) -> tuple[dict, dict]:
    canon: dict[tuple, dict] = {}
    repro: dict[tuple, list[dict]] = defaultdict(list)
    for row in rows:
        key = (row["base_request_id"], row["variant"])
        if row["phase"] == "canon":
            canon[key] = row
        elif row["phase"] == "repro":
            repro[key].append(row)
    return canon, repro


def build_report(seed: int = 42) -> dict:
    """Validate both cached sweeps, then compute the placement report."""
    sweeps = {}
    for tier, results_dir in (("external", EXTERNAL_DIR), ("local", LOCAL_DIR)):
        rows = load_rows(results_dir / "decisions.jsonl")
        validation = validate_rows(rows, results_dir, seed=seed, check_cache=True)
        canon, repro = _index(rows)
        sweeps[tier] = {
            "canon": canon, "repro": repro, "base_ids": validation["base_ids"],
        }
    bids = sweeps["external"]["base_ids"]
    if set(bids) != set(sweeps["local"]["base_ids"]):
        raise SystemExit("external and local sweeps cover different request sets")

    requests = {req.request_id: req for req in generate(seed)}
    missing = [bid for bid in bids if bid not in requests]
    if missing:
        raise SystemExit(f"requests not regenerated by seed {seed}: {missing[:3]}")

    placement = {bid: place(requests[bid]) for bid in bids}

    def routed_rows(tier_of):
        rows = []
        repro_by_bid = {}
        for bid in bids:
            variant, tier = placement[bid][0], tier_of(bid)
            rows.append(sweeps[tier]["canon"][bid, variant])
            repro_by_bid[bid] = sweeps[tier]["repro"][bid, variant]
        return rows, repro_by_bid

    systems: dict[str, dict] = {}
    for name, tier_of in (
        ("PLACEMENT", lambda bid: placement[bid][1]),
        ("ROUTER_ALL_EXTERNAL", lambda bid: "external"),
        ("ROUTER_ALL_LOCAL", lambda bid: "local"),
    ):
        rows, repro_by_bid = routed_rows(tier_of)
        systems[name] = _policy_metrics(rows)
        systems[name]["repro_modal_share_mean"] = _repro_modal_mean(repro_by_bid)
    for name, tier in (("FIXED_A3_EXTERNAL", "external"), ("FIXED_A3_LOCAL", "local")):
        rows = [sweeps[tier]["canon"][bid, "A3"] for bid in bids]
        systems[name] = _policy_metrics(rows)
        systems[name]["repro_modal_share_mean"] = _repro_modal_mean(
            {bid: sweeps[tier]["repro"][bid, "A3"] for bid in bids}
        )

    tier_share = Counter(tier for _, tier, _, _ in placement.values())
    local_share = tier_share.get("local", 0) / len(bids)
    report = {
        "schema": "placement_eval_v1",
        "n_requests": len(bids),
        "placement_rule_source": (
            "runtime/placement.py::place (autonomy variant from runtime/router.py::route, "
            "tier: personal data stays local)"
        ),
        "tier_distribution": dict(sorted(tier_share.items())),
        "local_share": local_share,
        "variant_distribution": dict(sorted(Counter(
            variant for variant, _, _, _ in placement.values()
        ).items())),
        "per_request_placement": {
            bid: {
                "variant": placement[bid][0],
                "tier": placement[bid][1],
                "variant_rule": placement[bid][2],
                "tier_rule": placement[bid][3],
            }
            for bid in bids
        },
        "systems": systems,
        "honesty_notes": [
            "all runtime/router.py notes apply (idealized pre-parse, lexical injection screen, no outcome tuning, cached-row reselection)",
            "tier rule is a hand-written policy statement; zero personal-data egress is a design property, the measured outputs are local share and the resulting policy metrics",
            "external comparator is one provider model, not a frontier ceiling; local tier is one small open-weight model",
            "an escalate outcome is the hand-off to a human, whichever tier produced it",
        ],
    }
    return report


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Evaluate egress-aware placement over both cached sweeps"
    )
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()
    report = build_report(args.seed)
    out_path = LOCAL_DIR / "placement_eval.json"
    _write_report_atomic(out_path, report)

    print(
        f"n={report['n_requests']} tiers: {report['tier_distribution']} "
        f"(local share {report['local_share']:.3f}) "
        f"variants: {report['variant_distribution']}"
    )
    header = (
        f"{'system':20s} {'mismatch':>9s} {'unsafe':>7s} {'inj-uns':>8s} "
        f"{'hard-esc':>9s} {'repro':>7s} {'calls':>6s}"
    )
    print(header)
    for name, m in report["systems"].items():
        def fmt(x, digits=3):
            return "  n/a" if x is None else f"{x:.{digits}f}"
        print(
            f"{name:20s} {fmt(m['policy_mismatch_rate']):>9s} "
            f"{fmt(m['unsafe_approval_rate']):>7s} {fmt(m['injected_unsafe_rate']):>8s} "
            f"{fmt(m['hard_escalate_rate']):>9s} {fmt(m['repro_modal_share_mean']):>7s} "
            f"{fmt(m['mean_llm_calls'], 2):>6s}"
        )
    print(f"wrote {out_path}")


if __name__ == "__main__":
    main()
