"""Emit strict, data-derived TeX macros from ``results/metrics.json``."""
from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Callable

ROOT = Path(__file__).resolve().parents[1]
WNAME = {"A0": "Zero", "A1": "One", "A2": "Two", "A3": "Three"}


def _finite(value, name: str) -> float:
    if not isinstance(value, (int, float)) or not math.isfinite(value):
        raise ValueError(f"missing or non-finite metric {name}: {value!r}")
    return float(value)


def pct(value, name: str) -> str:
    return f"{_finite(value, name) * 100:.1f}\\%"


def one(value, name: str) -> str:
    return f"{_finite(value, name):.1f}"


def integer(value, name: str) -> str:
    return f"{round(_finite(value, name)):,}"


def seconds(value, name: str) -> str:
    return f"{_finite(value, name) / 1000:.1f}"


Formatter = Callable[[object, str], str]

# Existing macro names remain available while their source keys and surrounding
# prose become explicit about regime and semantics.
METRICS: dict[str, tuple[str, Formatter]] = {
    "repro": ("repro_modal_share_mean", pct),
    "rpair": ("repro_pairwise_agreement_mean", pct),
    "funa": ("repro_unanimous_frac", pct),
    "fprec": ("faith_precision_macro", pct),
    "frec": ("faith_recall_macro", pct),
    "fpmicro": ("faith_precision_micro", pct),
    "frmicro": ("faith_recall_micro", pct),
    "jac": ("counterfactual_sensitivity_agreement_mean", pct),
    "cexact": ("counterfactual_exact_match_rate", pct),
    "mism": ("canonical_policy_mismatch_rate", pct),
    "unsafe": ("canonical_unsafe_approval_rate", pct),
    "smism": ("sampled_policy_mismatch_rate", pct),
    "sunsafe": ("sampled_unsafe_approval_rate", pct),
    "hacc": ("hard_policy_accuracy_rate", pct),
    "hesc": ("hard_escalate_rate", pct),
    "hunsafe": ("hard_unsafe_rate", pct),
    "inj": ("canonical_unsafe_approval_on_injected_cases_rate", pct),
    "sinj": ("sampled_unsafe_approval_on_injected_cases_rate", pct),
    "calls": ("mean_llm_calls", one),
    "lat": ("mean_latency_ms", seconds),
    "tok": ("mean_tokens_total", integer),
    "probeN": ("counterfactual_probe_n", integer),
}


def _required(mapping: dict, key: str, context: str = "metrics"):
    if key not in mapping:
        raise KeyError(f"{context} missing required key {key!r}")
    return mapping[key]


def render(
    metrics: dict, macro_prefix: str = "", source: str = "results/metrics.json",
) -> str:
    if _required(metrics, "schema_version") < 2:
        raise ValueError("metrics.json predates the validated schema; rerun harness.metrics")
    if macro_prefix and not macro_prefix.isalpha():
        raise ValueError(f"macro prefix must be letters only, got {macro_prefix!r}")
    metadata = _required(metrics, "metadata")
    variants = _required(metrics, "variants")
    for variant in WNAME:
        if variant not in variants:
            raise KeyError(f"metrics.json missing variant {variant}")

    n_requests = int(_required(metrics, "n_requests"))
    n_repro = int(_required(metrics, "n_repro"))
    hard_n = int(_required(metrics, "hard_n"))
    adversarial_n = int(_required(metrics, "adversarial_n"))
    temperatures = _required(metadata, "temperatures", "metadata")
    p = macro_prefix
    lines = [
        f"% Auto-generated by harness/make_expose_numbers.py from {source}.",
        "% Do not edit by hand.",
        f"\\newcommand{{\\{p}Nreq}}{{{n_requests}}}",
        f"\\newcommand{{\\{p}Nrepro}}{{{n_repro}}}",
        f"\\newcommand{{\\{p}Nhard}}{{{hard_n}}}",
        f"\\newcommand{{\\{p}Nadv}}{{{adversarial_n}}}",
        f"\\newcommand{{\\{p}Tcanon}}{{{one(_required(temperatures, 'canonical', 'temperatures'), 'temperature.canonical')}}}",
        f"\\newcommand{{\\{p}Trepro}}{{{one(_required(temperatures, 'sampled', 'temperatures'), 'temperature.sampled')}}}",
        f"\\newcommand{{\\{p}Tpert}}{{{one(_required(temperatures, 'perturbation', 'temperatures'), 'temperature.perturbation')}}}",
    ]
    for prefix, (key, formatter) in METRICS.items():
        for variant, word in WNAME.items():
            record = variants[variant]
            value = _required(record, key, variant)
            lines.append(
                f"\\newcommand{{\\{p}{prefix}{word}}}{{{formatter(value, f'{variant}.{key}')}}}"
            )
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate strict TeX metric macros")
    parser.add_argument("--results", default=str(ROOT / "results"))
    parser.add_argument("--output", default=str(ROOT / "expose" / "numbers.tex"))
    parser.add_argument("--macro-prefix", default="",
                        help="prefix every macro name (e.g. 'loc' -> \\locNreq); "
                             "default '' keeps the flagship output unchanged")
    args = parser.parse_args()
    metrics_path = Path(args.results) / "metrics.json"
    metrics = json.loads(metrics_path.read_text())
    try:
        source = str(metrics_path.resolve().relative_to(ROOT))
    except ValueError:
        source = str(metrics_path)
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    content = render(metrics, macro_prefix=args.macro_prefix, source=source)
    output.write_text(content)
    print(f"wrote {output} ({content.count('newcommand')} macros)")


if __name__ == "__main__":
    main()
